apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: currency-app-pvc
  namespace: currency-app-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
