name: demo-workflow
on: workflow_dispatch

env:
  DB_HOST: "10.0.20.5"
  DB_USER: "root"

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v4
      - name: update-ubuntu
        run: |
          apt update
          apt upgrade -y 
          apt install maven -y 